"""
Generated by generate/generate.py - 2020-08-02 00:44:10.775083
"""
from aiogithubapi.objects.repository.branch import AIOGitHubAPIRepositoryBranch
from tests.responses.repository.branch_fixtrue import branch_fixtrue_response


def test_branch_fixtrue(branch_fixtrue_response):
    obj = AIOGitHubAPIRepositoryBranch(branch_fixtrue_response)
    assert obj.name == branch_fixtrue_response["name"]
    assert obj.commit.sha == branch_fixtrue_response["commit"]["sha"]
    assert obj.commit.node_id == branch_fixtrue_response["commit"]["node_id"]
    assert obj.commit.commit.url == branch_fixtrue_response["commit"]["commit"]["url"]
    assert (
        obj.commit.commit.message
        == branch_fixtrue_response["commit"]["commit"]["message"]
    )
    assert (
        obj.commit.author.gravatar_id
        == branch_fixtrue_response["commit"]["author"]["gravatar_id"]
    )
    assert (
        obj.commit.author.avatar_url
        == branch_fixtrue_response["commit"]["author"]["avatar_url"]
    )
    assert obj.commit.author.url == branch_fixtrue_response["commit"]["author"]["url"]
    assert (
        obj.commit.author.login == branch_fixtrue_response["commit"]["author"]["login"]
    )
    assert obj.commit.url == branch_fixtrue_response["commit"]["url"]
    assert (
        obj.commit.committer.gravatar_id
        == branch_fixtrue_response["commit"]["committer"]["gravatar_id"]
    )
    assert (
        obj.commit.committer.avatar_url
        == branch_fixtrue_response["commit"]["committer"]["avatar_url"]
    )
    assert (
        obj.commit.committer.url
        == branch_fixtrue_response["commit"]["committer"]["url"]
    )
    assert (
        obj.commit.committer.login
        == branch_fixtrue_response["commit"]["committer"]["login"]
    )
    assert (
        obj.protection.required_status_checks.enforcement_level
        == branch_fixtrue_response["protection"]["required_status_checks"][
            "enforcement_level"
        ]
    )
    assert obj.protection_url == branch_fixtrue_response["protection_url"]
