"""
Generated by generate/generate.py - 2020-08-02 10:06:15.267428
"""
from aiogithubapi.objects.repository.label import AIOGitHubAPIRepositoryLabel
from tests.responses.repository.label_fixtrue import label_fixtrue_response


def test_label_fixtrue(label_fixtrue_response):
    obj = AIOGitHubAPIRepositoryLabel(label_fixtrue_response)
    assert obj.id == label_fixtrue_response["id"]
    assert obj.node_id == label_fixtrue_response["node_id"]
    assert obj.url == label_fixtrue_response["url"]
    assert obj.name == label_fixtrue_response["name"]
    assert obj.description == label_fixtrue_response["description"]
    assert obj.color == label_fixtrue_response["color"]
    assert obj.default == label_fixtrue_response["default"]
