name: Bug Report
description: Report a bug with aiogithubapi
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: Describe the issue you are experiencing. What were you trying to do and what happened?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: e.g., Ubuntu 22.04, macOS 14, Windows 11
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: e.g., 3.13, 3.14
    validations:
      required: true

  - type: input
    id: aiogithubapi-version
    attributes:
      label: aiogithubapi version
      placeholder: e.g., 24.6.0
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Problem-relevant code
      description: A minimal example to reproduce the bug
      render: python
      placeholder: |
        from aiogithubapi import GitHub

        # Your code here

  - type: textarea
    id: logs
    attributes:
      label: Traceback/Error logs
      description: If you have any trace or error logs, please provide them here
      render: txt

  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: Any other context about the problem
