"""
Generated by generate/generate.py - 2020-08-02 10:13:53.152051
"""
from aiogithubapi.objects.issue.label import AIOGitHubAPIIssueLabel
from tests.responses.issue.label_fixtrue import label_fixtrue_response


def test_label_fixtrue(label_fixtrue_response):
    obj = AIOGitHubAPIIssueLabel(label_fixtrue_response)
    assert obj.id == label_fixtrue_response["id"]
    assert obj.node_id == label_fixtrue_response["node_id"]
    assert obj.url == label_fixtrue_response["url"]
    assert obj.name == label_fixtrue_response["name"]
    assert obj.description == label_fixtrue_response["description"]
    assert obj.color == label_fixtrue_response["color"]
    assert obj.default == label_fixtrue_response["default"]
