"""
Class object for AIOGitHubAPIIssueLabel
Documentation: https://docs.github.com/en/rest/reference/issues#get-a-label

Generated by generate/generate.py - 2020-08-02 10:13:53.152051
"""
from aiogithubapi.objects.base import AIOGitHubAPIBase


class AIOGitHubAPIIssueLabel(AIOGitHubAPIBase):
    @property
    def id(self):
        return self.attributes.get("id", None)

    @property
    def node_id(self):
        return self.attributes.get("node_id", "")

    @property
    def url(self):
        return self.attributes.get("url", "")

    @property
    def name(self):
        return self.attributes.get("name", "")

    @property
    def description(self):
        return self.attributes.get("description", "")

    @property
    def color(self):
        return self.attributes.get("color", "")

    @property
    def default(self):
        return self.attributes.get("default", True)
